import { createContext, useContext, useState } from "react";
// Static import — the posts-data.js is auto-generated by the Vite plugin
// at build/dev start time, so it always exists before this module loads.
import { posts as allPosts } from "../generated/posts-data.js";

const BlogDataContext = createContext();

export function BlogDataProvider({ children }) {
  const [posts] = useState(allPosts);
  const loading = false;

  return (
    <BlogDataContext.Provider value={{ posts, loading }}>
      {children}
    </BlogDataContext.Provider>
  );
}

export function useBlogData() {
  const ctx = useContext(BlogDataContext);
  if (!ctx) throw new Error("useBlogData must be used within BlogDataProvider");
  return ctx;
}
