import { createContext, useContext, useState } from "react";
// Static import — the notes-data.js is auto-generated by the Vite plugin
// at build/dev start time, so it always exists before this module loads.
import { notes as allNotes, noteCategories as allCategories } from "../generated/notes-data.js";

const NotesDataContext = createContext();

export function NotesDataProvider({ children }) {
  const [notes] = useState(allNotes);
  const [noteCategories] = useState(allCategories);
  const loading = false;

  return (
    <NotesDataContext.Provider value={{ notes, noteCategories, loading }}>
      {children}
    </NotesDataContext.Provider>
  );
}

export function useNotesData() {
  const ctx = useContext(NotesDataContext);
  if (!ctx) throw new Error("useNotesData must be used within NotesDataProvider");
  return ctx;
}
